parameters:
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022
- name: RunTests
  type: boolean
  default: true

jobs:
- job: Windows
  timeoutInMinutes: 120
  pool: ${{ parameters.windowsPool }}
  variables:
    TestFilter: ""
  steps:
  - checkout: self
    fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
    clean: true
    submodules: true

  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud -ca'
    displayName: ⚙ Set build number

  - template: dotnet.yml
    parameters:
      RunTests: ${{ parameters.RunTests }}

- template: distributed-testing.yml
  parameters:
    windowsPool: ${{ parameters.windowsPool }}

- job: WrapUp
  dependsOn:
  - Windows
  - Testing
  pool: ${{ parameters.windowsPool }} # Use Windows agent because PublishSymbols task requires it (https://github.com/microsoft/azure-pipelines-tasks/issues/13821).
  condition: succeededOrFailed()
  steps:
  - checkout: self
    fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-symbols.yml
