trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
schedules:
- cron: "0 3 * * *" # Daily @ 8 PM PST
  displayName: Daily build
  branches:
    include:
    - main

parameters:
- name: SignSelection
  displayName: Sign?
  type: boolean
  default: false
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true

stages:

- stage: Build
  variables:
    TreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/
    SignSelection: ${{ parameters.SignSelection }}
    Codeql.Enabled: true

  jobs:
  - template: build.yml
    parameters:
      RunTests: ${{ parameters.RunTests }}

- template: prepare-insertion-stages.yml
